version: '3.8'

services:
  reservapp-db:
    image: mysql:8.0
    container_name: ReservAppDb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YES
      MYSQL_DATABASE: ReservAppDb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: